name: BuildAThing
version: '${project.version}'
main: buildathing.buildathing.Buildathing
api-version: 1.19
authors: [ morozoffnor ]
commands:
  starta:
    description: start-a-game
    usage: /<command>